"""Init

Revision ID: cce1cfa2bf46
Revises: 90145bcd91f4
Create Date: 2024-04-17 19:33:45.015978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce1cfa2bf46'
down_revision: Union[str, None] = '90145bcd91f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###
